Add : 회원가입 기능 구현
wecode-bootcamp-korea/28-1st-WEHAEYO-backend pull request #2
Opened 2022-01-01 03:51 UTC by leeay3

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- user 정보(이름, 이메일, 패스워드, 핸드폰번호)를 사용한 회원가입 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 기능 구현
- 정규식을 이용하여 유효성 검사
- 이메일 중복 체크
- 유효성 검사, 이메일 중복 체크를 통과하지 못 할 경우 에러 메세지를 반환 예외 처리 구현
- 패스워드 bcrypt를 이용하여 암호화

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- bcrypt가 무엇이며, 어떻게 코드에 적용시키는지를 알게됐습니다.
- 나 혼자 작업하는 프로젝트가 아니라 협업 프로젝트이기에 모델링을 생성/수정하는 방법이 달라졌고, git 사용법도 혼자할 때와 차이가 있음을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 실무에서 validation 사용 시 views.py에 넣는 방법과 따로 파일을 생성하여 빼는 방법 중 어떤 방법을 더 많이 선호 하는지 궁금합니다. 제가 생각 했을 때, 따로 빼는 방법이 더 효율적이라고 생각합니다.

2022-01-01 07:04 UTC, kyeongraekim requested changes
아영님~ 전반적으로 깔끔하게 잘 작성해주셨네요 굉장히 마이너한 수정 사항 만 아래 보시고 반영해주세요!~

2022-01-01 07:04 UTC, kyeongraekim commented on users/views.py
> +            if not is_email_valid(email):
함수명 선언에 있어서 의문문처럼 보이는 것이 아니라 평서문 처럼 보이는 "is_valid_email" 이 보다 정확한 표현일 것 같네요~

2022-01-01 08:05 UTC, leeay3 commented on users/views.py
> +            if not is_email_valid(email):
수정 완료하였습니다.

2022-01-01 08:35 UTC, kyeongraekim approved these changes
LGTM!~

2022-01-01 08:36 UTC, merged

2022-01-02 06:59 UTC, leeay3 commented
<img width="716" alt="스크린샷 2021-12-31 오후 4 13 58" src="https://user-images.githubusercontent.com/87291008/147868678-bafe51d8-8326-41de-ab17-1974a91e9497.png">
<img width="707" alt="스크린샷 2021-12-31 오후 4 13 46" src="https://user-images.githubusercontent.com/87291008/147868681-83854ae8-7706-43e6-a331-a882510648f8.png">