[이찬영] db_uploader.py 작성 및 modeling 수정
wecode-bootcamp-korea/28-1st-WEHAEYO-backend pull request #3
Opened 2022-01-01 15:48 UTC by coldzero94

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- upload.py를 통한 db 통일화 구성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. one to one 관계 설정 해서 user 데이터 입력
2. one to many 관계 설정 및 user 데이터 입력
3. many to many 관계 설정 및 user 데이터 입력
4. csv, upload.py 파일 gitignore 처리

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- csv 파일의 작성법 및 deb 모델링에 대해서 완벽하게 이해하게 되었습니다.
- upload.py를 작성할때, 1 to 1은 빠르게 이해하였지만, forien key, many to many field 작성할때 관계를 이해하는것에 어려움을 많이 겪었습니다.
- many to many 에서 작성하기 위해 .add 알 수 있었습니다.
- filter 를 통하 id matching으로 m2m 매칭 하는 법에 대해서 공부하게되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- m2m 필드에 대해서 작성할때에 무척 어려웠는데, 참고할 만한 사이트가 django 공식 문서 many to many 말고 따른곳이 있을까요?

2022-01-01 16:11 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해주세요!~

2022-01-01 16:11 UTC, kyeongraekim commented on payments/models.py
> +    quantity     = models.IntegerField()
기본 수량의 default 값을 설정해주셔야 할 것 같네요!~ 몇으로 디폴트를 주면 좋을지 한 번 고민해보세요!~

2022-01-01 16:11 UTC, kyeongraekim commented on reviews/models.py
>      user        = models.ForeignKey(User, on_delete=models.CASCADE)
웹서비스 기획상 유저가 사라진다고 해도 해당 리뷰가 사라져야만 할까요? ㅎㅎ null 값으로 비어지는 기획은 어떨지 한 번 고민해보세요!~

2022-01-01 16:11 UTC, kyeongraekim commented on reviews/models.py
> +    price      = models.DecimalField(max_digits=10, decimal_places=2)
이제 해당 내용을 잘 이해해주셨을거라 생각됩니다!~ 두 번에 거친 리뷰가 전 단계에 있었으니 꼭 블로그를 통한 기록정리를 잊지 말아주세요~

2022-01-01 16:13 UTC, kyeongraekim commented
찬영님 혹시 슬랙으로 보내주신 db_uploader 와 관련 csv 파일 내 데이터가 잘 들어갔는지 스샷을 통한 확인 부탁드려도 될까요?

2022-01-01 17:04 UTC, coldzero94 commented on payments/models.py
> +    quantity     = models.IntegerField()
default 0 로 설정하였습니다~

2022-01-01 17:05 UTC, coldzero94 commented on reviews/models.py
>      user        = models.ForeignKey(User, on_delete=models.CASCADE)
말씀하신 의견에 충분히 공감하였습니다 ㅎ
user 지워지면, set ull로 변경 하였습니다~! 
좋은 의견 감사드립니다!

2022-01-01 17:06 UTC, coldzero94 commented on reviews/models.py
> +    price      = models.DecimalField(max_digits=10, decimal_places=2)
당연히 정리하겠습니다~! 변화점 중요하게 다시한번 언급해 주셔서 감사합니다~!

2022-01-01 17:24 UTC, coldzero94 commented
![스크린샷, 2022-01-02 02-10-47](https://user-images.githubusercontent.com/89123869/147856315-901057b0-77cb-49e9-af70-669adefffe54.png)
![스크린샷, 2022-01-02 02-22-47](https://user-images.githubusercontent.com/89123869/147856322-378a95ee-e41b-45e1-bfa0-3ed07df6a721.png)
![스크린샷, 2022-01-02 02-22-59](https://user-images.githubusercontent.com/89123869/147856323-28d0c4ee-e902-4b87-94c0-dde55ba8e398.png)
![스크린샷, 2022-01-02 02-23-13](https://user-images.githubusercontent.com/89123869/147856328-108ff0dc-9234-49aa-ad33-3c365ecc36d9.png)
![스크린샷, 2022-01-02 02-23-23](https://user-images.githubusercontent.com/89123869/147856331-93454685-3e10-4bb0-9f2f-1f478a13e0bb.png)

2022-01-02 01:03 UTC, kyeongraekim approved these changes
LGTM!~ 상품 메인페이지 뷰 바로 작성 시작해주세요!~

2022-01-02 01:04 UTC, merged