Add : 로그인 기능 구현
wecode-bootcamp-korea/28-1st-WEHAEYO-backend pull request #4
Opened 2022-01-02 06:52 UTC by leeay3

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현
- 프론트와 통신 테스트

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 로그인 뷰 작성
- 로그인 시 jwt 발급
- 로그인 데코레이터 구현
- 프론트와 백엔트 통신 테스트

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데코레이터의 이해가 부족하여 기능 구현과 응용이 어려웠습니다.
- 같은 와이파이가 아니였을 경우 ngrok를 이용하여 프론트/백엔드 통신이 가능하다는 점을 알게 됐습니다.
- ngrok를 사용하여 통신하는 방법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-01-02 06:57 UTC, leeay3 commented
![Uploading 스크린샷 2022-01-02 오후 3.05.37.png…]()

2022-01-02 06:58 UTC, leeay3 commented
<img width="650" alt="스크린샷 2022-01-02 오후 3 05 37" src="https://user-images.githubusercontent.com/87291008/147868654-15bc8eec-4702-4852-b61a-98465298d17b.png">
<img width="489" alt="스크린샷 2022-01-02 오후 3 15 38" src="https://user-images.githubusercontent.com/87291008/147868657-32f021bd-04d3-473b-a5ad-f8a9c5c13956.png">

2022-01-02 11:31 UTC, kyeongraekim requested changes
아영님~ 아래 내용 확인 후 수정 반영해주세요!~ 전반적으로 깔끔하게 잘 작성해주신 편인 것 같습니다!~

2022-01-02 11:31 UTC, kyeongraekim commented on users/views.py
> +                "user_id" : user_info.id,
- 토큰이 탈취되어 악용 될 수 있는 경우를 고려하여 payload의 키 형태로 닮길 내용을 구체적인 내용의 "user_id" 에서 일반적인 내용의 "id" 로 변경하는 것은 어떨까요? 
- 추가로 같이 올려주신 데코레이터에서 토큰의 id 값을 매핑하는데 현재 올려주신 토큰 생성 코드에는 id 값이 아니라 user_id 로 적혀있어서 키에러가 필연적으로 날 것 같아 보이네요!~

2022-01-02 11:31 UTC, kyeongraekim commented on users/views.py
> +            return JsonResponse({'message':'INVALID_JSON'}, status=400)
리턴 메세지의 의미가 조금 모호해 보입니다. INVALID_JSON_FORMAT 정도로 바꾸면 보다 명확해질 것 같습니다.

2022-01-02 11:31 UTC, kyeongraekim commented on users/views.py
> +            return JsonResponse({'message':'INVALID_JSON'}, status=400)
해당 내용도 리턴 메세지를 읽게 될 프론트 단을 위해 보다 명확한 메세지로 전달해주세요~

2022-01-02 11:31 UTC, kyeongraekim commented on users/views.py
> +
hashed_password = user.password.encode("utf-8")


위와 같은 내용을 추가하여 변수명에 담아 주면 아래와 같이 제 3자의 가독성이 조금은 더 향상 될 수 있겠네요!~
해당 내용은 수정 필수 요소는 아니오니 위와 같이 매끄러운 독해를 돕는 방향성도 고려해보세요!~

```python
if not bcrypt.checkpw(password.encode('utf-8'), hashed_password)

2022-01-02 11:31 UTC, kyeongraekim commented on users/views.py
> +from datetime     import datetime, timedelta
컨벤션상 서로 상이한 내용이 이어지는 import 문이기 때문에 라인 스페이싱을 한칸 추가 해주세요!~

2022-01-02 11:31 UTC, kyeongraekim commented on users/utils.py
> +            return JsonResponse({"error_code":"INVALID_LOGIN"}, status=401)
해당 내용은 Token이 담겨있어야 하는 "Authorization"이 request 객체에 없을 때 리턴 될 메세지이기 떄문에 key_error_authorization 정도가 더 명확한 에러 메세지가 되겠네요!~

2022-01-02 11:31 UTC, kyeongraekim commented on users/utils.py
> +            user = User.objects.get(id = data["id"])
이 부분은 아래 로그인 뷰와 같이 맞물려서 리뷰가 달려있는데 확인 부탁드릴게요!~

2022-01-02 11:34 UTC, leeay3 commented on users/views.py
> +                "user_id" : user_info.id,
넵~ 수정 완료했습니당!

2022-01-02 11:35 UTC, leeay3 commented on users/views.py
> +            return JsonResponse({'message':'INVALID_JSON'}, status=400)
넵~ 수정 완료했습니당!

2022-01-02 11:35 UTC, leeay3 commented on users/views.py
> +            return JsonResponse({'message':'INVALID_JSON'}, status=400)
넵~ 수정 완료했습니당!

2022-01-02 11:36 UTC, leeay3 commented on users/views.py
> +from datetime     import datetime, timedelta
넵~ 수정 완료했습니당!

2022-01-02 11:37 UTC, leeay3 commented on users/utils.py
> +            return JsonResponse({"error_code":"INVALID_LOGIN"}, status=401)
넵~ 수정 완료했습니당!

2022-01-02 12:32 UTC, kyeongraekim requested changes
요청드린 사항은 잘 반영해주셨네요! 마지막으로 디렉토리와 파일명 관련 수정 사항 반영해주세요!~

2022-01-02 12:32 UTC, kyeongraekim commented on users/utils.py
> +
해당 utils.py 는 users 앱 말고 다른 앱에서도 용도가 굉장히 많을 것임으로 다른 app들이 위치한 동일한 곳에서 utils라는 디렉토리를 만들어주시고, login_decorator.py 라는 파일안에 아래 코드 내용을 옮겨 담아주세요!~

2022-01-03 03:20 UTC, leeay3 commented on users/views.py
> +
넵~ 수정 완료했습니당!

2022-01-03 03:20 UTC, leeay3 commented on users/utils.py
> +
넵~ 수정 완료했습니당!

2022-01-03 03:24 UTC, leeay3 commented on users/utils.py
> +            user = User.objects.get(id = data["id"])
넵~ 수정 완료했습니당!

2022-01-03 04:34 UTC, kyeongraekim approved these changes
LGTM!~

2022-01-03 04:34 UTC, merged