[이찬영] restaurants list page 구현
wecode-bootcamp-korea/28-1st-WEHAEYO-backend pull request #7
Opened 2022-01-04 17:07 UTC by coldzero94

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 별점순, 리뷰순, 기본순(가나다순)으로 음식점 목록페이지 구성
- query string으로 데이터 전달

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. sorting 기능 추가
- annotate에 avg,count를 통한 평점 및 리뷰수 데이터 전송
- order_by를 통한 가,나,다순 정렬 기능

2. error메세지 설정
- json decode error 설정, json type 데이터가 아닐경우 구현
- Category.DoesNotExist error 설정, 카테고리가 없을경우 구현
- key error 시 구현

3. query string 설정
- url 주소에 따른 기본 설정은 category로 들어올 수 있도록 설정
- 이름에 따라 설정된 데이터 전송 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 역참조 개념을 통해서 식당의 이미지를 갖고 오는 법을 배울 수 있었습니다.
- annotate를 이용한 평점순, 리뷰순 그리고 가나다 순으로 정렬 방법에 대해서 알게 되었습니다.
- 에러메세지 다변화를 통해 프론트 입장에서 송신오류 났을때 좀 더 자세하게 알려줄 수 있는 방법에 대해서 고민하였습니다.
- query string을통한 url주소에 따라서 맞춤 데이터를 전송해주는 것에대해서 고민하고 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 좀더 코드를 간편화하게 짜는법에 대해서 알고 싶습니다. 특히 restaurants = Resaturant로 시작하는 긴 코드를 줄여보고 싶습니다.

2022-01-05 01:20 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2022-01-05 01:20 UTC, kyeongraekim commented on restaurants/views.py
> +                          .order_by(sorts)
annotate 기능을 잘 접목시켜 주셨네요. 다만 구분을위한 슬래쉬 부분을 과도하게 사용해주실 필요는 없으십니다!~

2022-01-05 01:20 UTC, kyeongraekim commented on restaurants/views.py
> +        except:
해당 부분은 다시 한번 디버깅시 어떠한 에러가 나왔는지 파악하기 어렵게 모든 에러를 FAILED 라는 메세지로 수렴하는 결과를 내놓겠네요!~ 해당 부분 삭제 해주셔도 무방해보입니다.

2022-01-05 01:20 UTC, kyeongraekim commented on restaurants/views.py
> +class ListPageView(View):
ListPageView라는 페이지 관점에서의 클래스 명보다는 RestaruantsListView 정도가 더 데이터 적 관점에 입각한 올바른 네이밍처럼 보이네요!~ 향후 확장성을 고려하여 접근해보세요!~

2022-01-05 01:23 UTC, kyeongraekim commented on restaurants/views.py
> +                          .order_by(sorts)
그리고 혹시 첫 화면에서 보여질 레스토랑 서치 기능은 따로 없으실까요? ㅎㅎ

2022-01-05 16:04 UTC, coldzero94 commented on restaurants/views.py
> +class ListPageView(View):
말씀하신 사항 적용 하였습니다~

2022-01-05 16:05 UTC, coldzero94 commented on restaurants/views.py
> +        except:
말씀하신 사항 적용 하고 Fielderror 추가하였습니다.

2022-01-05 16:08 UTC, coldzero94 commented on restaurants/views.py
> +                          .order_by(sorts)
슬래쉬 부분은 삭제하였습니다. 그리고 레스토랑 서치기능은 구현 못하였습니다 ㅜㅜ

2022-01-06 02:08 UTC, kyeongraekim requested changes
아래 내용 확인 후 답변주시면 감사하겠습니다 찬영님!~

2022-01-06 02:08 UTC, kyeongraekim commented on restaurants/views.py
> +            restaurant_name = request.GET.get('name',None)
None앞에 스페이싱 한칸씩만 해주세요!~

2022-01-06 02:08 UTC, kyeongraekim commented on restaurants/views.py
> +
sort 값은 프론트에서 어떤 키 값 형 태로 주고 받으시는건가요? 코멘트 아래에 남겨주세요!~

2022-01-06 04:59 UTC, coldzero94 commented on restaurants/views.py
> +
http -v GET http://127.0.0.1:8000/restaurants/list -> 전체페이지
http -v GET http://127.0.0.1:8000/restaurants/list?sort=-review_count -> 리뷰수에 따른 정렬
http -v GET http://127.0.0.1:8000/restaurants/list?category=korean -> 한식페이지 전송(기본 정렬에 따른 가나다순)
http -v GET http://127.0.0.1:8000/restaurants/list?category=korean&sort-avg_rating -> 별점순에 따른 정렬
입니다. 이렇게 전송하고 있습니다!

2022-01-06 09:48 UTC, coldzero94 commented
수정사항 반영하여서 push 완료 하였습니다.

2022-01-06 10:36 UTC, kyeongraekim approved these changes

2022-01-06 10:36 UTC, merged